//package jdbcdemo.dao;
//
//
//import java.sql.ResultSet;
//import java.sql.SQLException;
////import java.sql.Statement;
//import java.util.ArrayList;
//import java.util.List;
//
////import jdbcdemo.domain.Egzamin;
//import jdbcdemo.domain.Instruktor;
//
//
//public class InstruktorRepository extends RepositoryBase<Instruktor> {
//
//	
//
//	private static final String createTableSql = "CREATE TABLE instruktor(id BIGINT GENERATED BY DEFAULT AS IDENTITY, imie VARCHAR(20), nazwisko VARCHAR(50))";
//	private static final String insertSql = "INSERT INTO INSTRUKTOR (imie, nazwisko) VALUES (?,?)"; 																							
//	private static final String updateSql = "UPDATE INSTRUKTOR SET (imie, nazwisko) = (?,?) WHERE id=?";
//	private static final String deleteSql = "DELETE FROM INSTRUKTOR WHERE id=?";
//	private static final String selectAllSql = "SELECT * FROM INSTRUKTOR";
//
//
//
//	public InstruktorRepository() {
//		super();
//
//		
//	}
//
//	public List<Instruktor> getAll() throws SQLException {
//		List<Instruktor> result = new ArrayList<Instruktor>();
//		try {
//			ResultSet rs = selectAll.executeQuery();
//			while (rs.next()) {
//				Instruktor i = new Instruktor();
//				i.setId(rs.getLong("id"));
//				i.setImie(rs.getString("imie"));
//				i.setNazwisko(rs.getString("nazwisko"));
//				result.add(i);
//			}
//
//		} catch (SQLException e) {
//			e.printStackTrace();
//		}
//		return result;
//	}
//
//	public void add(Instruktor instruktor) throws SQLException {
//
//		insert.setString(1, instruktor.getImie());
//		insert.setString(2, instruktor.getNazwisko());
//		insert.executeUpdate();
//
//	}
//
//	public void update(Instruktor instruktor) {
//
//		try {
//			update.setString(1, instruktor.getImie());
//			update.setString(2, instruktor.getNazwisko());
//			update.setLong(3, instruktor.getId());
//			update.executeUpdate();
//		} catch (SQLException ex) {
//			ex.printStackTrace();
//		}
//	}
//
//	public void delete(Instruktor instruktor) throws SQLException {
//
//		delete.setLong(1, instruktor.getId());
//		delete.executeUpdate();
//
//	}
//
//	public void createTable() throws SQLException {
//
//		ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
//		boolean tableExists = false;
//		while (rs.next()) {
//			if (rs.getString("TABLE_NAME").equalsIgnoreCase("instruktor")) {
//				tableExists = true;
//				break;
//			}
//		}
//		if (!tableExists)
//			createTable.executeUpdate(createTableSql);
//	}
//
//	@Override
//	protected String deleteSql() {
//		return deleteSql;
//	}
//
//	@Override
//	protected String updateSql() {
//		return updateSql;
//	}
//
//	@Override
//	protected String insertSql() {
//		return insertSql;
//	}
//
//	@Override
//	protected String selectAllSql() {
//		return selectAllSql;
//	}
//
//
//
//}
