//package jdbcdemo.dao;
//
//import java.sql.Connection;
//import java.sql.DriverManager;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
//import java.sql.SQLException;
//import java.sql.Statement;
//import java.util.ArrayList;
//import java.util.List;
//
//import jdbcdemo.domain.Egzamin;
//import jdbcdemo.domain.Instruktor;
//import jdbcdemo.domain.Jazda;
//import jdbcdemo.domain.Kursant;
//import jdbcdemo.domain.Samochod;
//
//public class SamochodRepository extends RepositoryBase<Samochod> {
//	
//private static final String createTableSql = "CREATE TABLE samochod(id BIGINT GENERATED BY DEFAULT AS IDENTITY, marka VARCHAR(20), model VARCHAR(20), kolor VARCHAR(20), rokProdukcji INTEGER, nrRejestracyjny VARCHAR(10))"; // KLUCZ OBCY ID_INSTRUKTOR???
//	
//	private static final String insertSql = "INSERT INTO SAMOCHOD (marka, model, kolor, rokProdukcji, nrRejestracyjny) VALUES (?, ?, ?, ?, ?)";
//	private static final String updateSql = "UPDATE SAMOCHOD SET (imie, nazwisko, telefon, nrPesel, dataUrodzenia, rozpoczecieKursu) = (?, ?, ?, ?, ?, ?) WHERE id=?";
//	private static final String deleteSql = "DELETE FROM SAMOCHOD WHERE id=?";
//	private static final String selectAllSql = "SELECT * FROM SAMOCHOD";
//
//	@Override
//	protected String selectAllSql() {
//		// TODO Auto-generated method stub
//		return null;
//	}
//
//	@Override
//	protected String deleteSql() {
//		// TODO Auto-generated method stub
//		return null;
//	}
//
//	@Override
//	protected String updateSql() {
//		// TODO Auto-generated method stub
//		return null;
//	}
//
//	@Override
//	protected String insertSql() {
//		// TODO Auto-generated method stub
//		return null;
//	}
//
//	
//
//}
